return {
	"oncomouse/lushwal.nvim",
	cmd = { "LushwalCompile" },
	dependencies = {
		{ "rktjmp/lush.nvim" },
		{ "rktjmp/shipwright.nvim" },
	},
	config = function()
		vim.g.lushwal_configuration({
			compile_to_vimscript = true,
			addons = {
				ale = true,
				barbar = true,
				bufferline_nvim = true,
				coc_nvim = true,
				dashboard_nvim = true,
				fern_vim = true,
				gina = true,
				gitsigns_nvim = true,
				hop_nvim = true,
				hydra_nvim = true,
				indent_blankline_nvim = true,
				lightspeed_nvim = true,
				lspsaga_nvim = true,
				lsp_trouble_nvim = true,
				lualine = true,
				markdown = true,
				mini_nvim = true,
				native_lsp = true,
				neogit = true,
				neomake = true,
				nerdtree = true,
				nvim_cmp = true,
				nvim_tree_lua = true,
				nvim_ts_rainbow = true,
				semshi = true,
				telescope_nvim = true,
				treesitter = true,
				vim_dirvish = true,
				vim_gitgutter = true,
				vim_signify = true,
				vim_sneak = true,
				which_key_nvim = true,
			},
		})
	end,
}
